apiVersion: v1
kind: Service
metadata:
  name: sso-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sso-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
